package com.moomark.board.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorCode {
  DONT_KNOW_ERROR("DOESN'T KNOW ERROR", 100000),
  CANNOT_FIND_BOARD("CANNOT_FIND_BOARDINFO", 100001),
  CANNOT_FIND_CATEGORY("CANNOT_FIND_CATEGORYINFO", 100002),
  CANNOT_FIND_PARENT_CATEGORY("CANNOT_FIND_PARENT_CATEGORY", 100003),
  CANNOT_FIND_CHILD_CATEGORY("CANNOT_FIND_CHILD_CATEGORY", 100004),
  CANNOT_FIND_TAG_INFORMATION("CANNOT_FIND_TAG_INFORMATION", 100005),
  DOES_NOT_MATCH_BOARD_AND_TAG("DOES_NOT_MATCH_BOARD_AND_TAG", 100006),
  EXIST_MATCH_BOARD_AND_TAG("EXIST_MATCH_BOARD_AND_TAG", 100007);
  
  
  protected final String msg;
  protected final int code;
}
